### ISSUE TITLE
Variable font file naming (`*.var.*`) causes 500 Internal Server Error on Apache web server

### ISSUE THREAD

**Issue by Calinou** [philipbelesky/inter-ui#17]
As described here: https://serverfault.com/questions/159152/apache-treating-files-with-var-in-their-names-as-type-maps

Font file names such as `Inter.var.woff2` cause a cryptic issue related to the MultiViews feature supported by the Apache web server.

We should either rename those font files in a future version, or document the workaround in the README (and perhaps both, for posterity). Here, commenting out `AddHandler type-map var` in `mods-available/mime.conf` then restarting Apache did the trick for me.

**Comment by philipbelesky** [comment]
Hi, thanks for this report. I am relatively hesitant to rename the files as I suspect a large number of people are directly referencing the files from `node_modules` which makes name changes breaking. I'll think about the naming (along with #10) but agree a `README` note would be ideal. If you'd like to do a PR for that, please go ahead. Otherwise I'll try to get on to it soon.
