### ISSUE TITLE
Wrong files in subset directories

### ISSUE THREAD

**Issue by maximeg** [philipbelesky/inter-ui#24]
Hi (again!),

While looking at the repo, I noticed that in the subset directories (both latin and hinted latin), there were `Inter-Xxxx-subset.ext` files being the new generated ones and `Inter-Xxxx.ext` being old (10 month old).
![image](https://user-images.githubusercontent.com/252162/122667599-eff39000-d1b3-11eb-82ea-f752b35cc635.png)

The SCSS/CSS files reference `Inter-Xxxx.ext` files.

Maybe in your scripts, the

```sh
rename 's/-subset//' './Inter (web latin)/'*.woff*
```

part does not work because dest files exists. I don't know this command, I don't have it on zsh.

We may want to 

```sh
rm -fr './Inter (web latin)' && mkdir './Inter (web latin)'
```

beforehand.

**Comment by philipbelesky** [comment]
Thanks for bringing this to my attention and for the proposed fixes. I've tweaked the build script to do a full rm/mkdir for each of the directories and hopefully improved the naming. Let me know if there's anything you'd like to check/improve, and if you'd like to be added as a contributor in the `package.json`. Otherwise, I'll issue another point release with the updated files.

**Comment by maximeg** [comment]
I had a look, everything looks fine to me :)
I like the all options here, full vs latin, pure CSS files, only include specific font weight or choose font-display in SCSS. That is neat!

Here my details:

```json
    {
      "name": "Maxime Garcia",
      "email": "maxime.garcia@gmail.com",
      "url": "https://emaxime.com/"
    }
```

Thanks!

**Comment by philipbelesky** [comment]
No problem, I've added that credit it and pushed out `3.19.2`

**Comment by maximeg** [comment]
Thanks!
